/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tharindu
 */
import java.io.ByteArrayInputStream;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.util.Scanner;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.SourceDataLine;

public class Server extends javax.swing.JFrame {

    AudioInputStream audioInputStream;
    static AudioInputStream staticAudioInputStream;
    static AudioFormat audioFormat;
    static boolean stopCapture = true;
    static int sampleRate = 44100;
    static int stop=0;
    static DataLine.Info dataLineInfo;
    static SourceDataLine sourceDataLine;
    private static String ip,port;
    private static DatagramSocket datagramSocket ;
            
    public Server() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        txtIp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MIc Anyware");
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(510, 510));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.Color.lightGray);
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.setToolTipText("Mic Anyware");
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 383));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("IP Address");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 110, 116, 40);

        txtPort.setEditable(false);
        txtPort.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtPort.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        txtPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortActionPerformed(evt);
            }
        });
        jPanel1.add(txtPort);
        txtPort.setBounds(170, 180, 290, 40);

        txtIp.setEditable(false);
        txtIp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtIp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jPanel1.add(txtIp);
        txtIp.setBounds(170, 110, 290, 40);

        jLabel2.setBackground(new java.awt.Color(255, 255, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Port");
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 180, 116, 39);

        btnStart.setBackground(new java.awt.Color(255, 255, 0));
        btnStart.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 102, 0));
        btnStart.setText("Start");
        btnStart.setBorder(new javax.swing.border.MatteBorder(null));
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jPanel1.add(btnStart);
        btnStart.setBounds(20, 330, 150, 70);

        btnStop.setBackground(new java.awt.Color(255, 255, 0));
        btnStop.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnStop.setForeground(new java.awt.Color(255, 102, 0));
        btnStop.setText("Stop");
        btnStop.setBorder(new javax.swing.border.MatteBorder(null));
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });
        jPanel1.add(btnStop);
        btnStop.setBounds(310, 330, 150, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SKDNFK.jpg"))); // NOI18N
        jLabel4.setAlignmentY(0.0F);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 500, 500);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 500);

        jMenuBar1.setBackground(new java.awt.Color(255, 0, 51));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 204));

        jMenu1.setText("New Client");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Exit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        
        new Thread() {
            @Override
            public void run() {
                Cali();
            }
        }.start();

    }//GEN-LAST:event_btnStartActionPerformed
    public static void Cali() {
        
        stop=0;
        try {
            datagramSocket=new DatagramSocket(Integer.parseInt(port));
            byte tempBuffer[] = new byte[1024];

            float sampleRate = 44100.0F;
            int sampleSizeInBits = 16;
            int channels = 1;
            boolean signed = true;
            boolean bigEndian = false;

            audioFormat = new AudioFormat(sampleRate, sampleSizeInBits, channels, signed, bigEndian);
            dataLineInfo = new DataLine.Info(SourceDataLine.class, audioFormat);

            sourceDataLine = (SourceDataLine) AudioSystem.getLine(dataLineInfo);
            sourceDataLine.open(audioFormat);
            sourceDataLine.start();

            DatagramPacket datagramPacket = new DatagramPacket(tempBuffer, tempBuffer.length);
            ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(datagramPacket.getData());
                
            while (stopCapture == true) {
             
                datagramSocket.receive(datagramPacket);
                staticAudioInputStream = new AudioInputStream(byteArrayInputStream, audioFormat, datagramPacket.getLength());

                try {
                    byte soundbytes[] = datagramPacket.getData();
                    sourceDataLine.write(soundbytes, 0, soundbytes.length);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

            sourceDataLine.drain();
            sourceDataLine.close();

        } catch (Exception e) {
            System.err.println(e);
        }
    }

    private void txtPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        new Thread() {
            @Override
            public void run() {
                
                stop=1;  
                datagramSocket.close();
            }
        }.start();
             
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Scanner s=new Scanner(System.in);
                System.out.println("Enter Server's IP Adress");
                ip=s.next();
                System.out.println("Enter a Port Number");
                port=s.next();
                new Server().setVisible(true);
                txtPort.setText(port);
                txtIp.setText(ip);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JTextField txtIp;
    private static javax.swing.JTextField txtPort;
    // End of variables declaration//GEN-END:variables
}
